env:
  - GO111MODULE=on
  #- GOPROXY=https://gocenter.io
before:
  hooks:
    - go mod download
builds:
- main: ./cmd/seed/main.go
  id: seed
  binary: seed
  env:
    - CGO_ENABLED=0
  goos: 
    - darwin
    - linux
    - windows
  goarch:
    - 386
    - amd64
    - arm
    - arm64
- main: ./cmd/cli/main.go
  id: cli
  binary: cli
  env:
    - CGO_ENABLED=0
  goos: 
    - darwin
    - linux
    - windows
  goarch:
    - 386
    - amd64
    - arm
    - arm64
archives:
- name_template: '{{ .ProjectName }}_{{.Tag}}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
  format_overrides:
  - goos: windows
    format: zip
release:
  github:
  prerelease: auto
